name: 8051
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
    build_only:
      uses: ./.github/workflows/embedded-build.yml
      secrets: inherit
      with:
        board: "CH55xDuino.mcs51.ch552"
        build_type: 'build_only'  # Change to 'build_and_test' if you want to run tests
        skip_all_builds: "skip" # Skips all builds but sets up the environment for testing
        s8051_build: 'build' # Build the 8051 client

