name: Arm Cortex M4 Atmega SAMD51
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
    build_and_test:
      uses: ./.github/workflows/embedded-build.yml
      secrets: inherit
      with:
        board: "adafruit:samd:adafruit_feather_m4"

