name: Embedded Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  arduino_builds:
    #strategy:
    #  matrix:
    #    board: [ "adafruit:samd:adafruit_feather_m4" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Copy required files
        run: |
            ls -l
            cp ./tests/client/test_bmodbus_client.c ./tests/arduino/arduino_client_example/test_bmodbus_client.c
            cp ./tests/unity/unity.c ./tests/arduino/arduino_client_example/unity.c
            cp ./tests/unity/unity.h ./tests/arduino/arduino_client_example/unity.h
            cp ./tests/unity/unity_internals.h ./tests/arduino/arduino_client_example/unity_internals.h
            cp ./bmodbus.h ./tests/arduino/arduino_client_example/bmodbus.h
            cp ./bmodbus.c ./tests/arduino/arduino_client_example/bmodbus.c
      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Setting up Arduino CLI libraries
        run: |
          arduino-cli config init
          arduino-cli config set board_manager.additional_urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          arduino-cli core update-index
          arduino-cli core install adafruit:samd
      - name: Compile Sketch
        run: |
          cd ./tests/arduino
          arduino-cli compile --fqbn "adafruit:samd:adafruit_feather_m4" --build-property "compiler.c.extra_flags=-DUNITY_OUTPUT_CHAR=uut_serial_write"  --build-property "compiler.cpp.extra_flags=-DUNITY_OUTPUT_CHAR=uut_serial_write" --export-binaries arduino_client_example
#          arduino-cli config init
#          arduino-cli config set board_manager.additional_urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
#          arduino-cli core update-index
#          arduino-cli core install adafruit:samd
#          arduino-cli compile --fqbn adafruit:samd:adafruit_feather_m4 ./tests/arduino/arduino_client_example
#      - name: Compile Sketch
#        uses: arduino/compile-sketches@v1.1.2
#        with:
#          sketch-paths: |
#            - ./tests/arduino/arduino_client_example
#          fqbn: "adafruit:samd:adafruit_feather_m4"
#          platforms: |
#            - name "adafruit:samd"
#            - source-url "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
#          verbose: 'true'
