name: Embedded Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  arduino_builds:
    #strategy:
    #  matrix:
    #    board: [ "adafruit:samd:adafruit_feather_m4" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Sketch
        uses: arduino/compile-sketches@v1.1.2
        with:
          sketch-paths: |
            - ./tests/arduino/arduino_client_example
          fqbn: "adafruit:samd:adafruit_feather_m4"
          platforms: | 
            - name "adafruit:samd"
            - source-url "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
          verbose: 'true'
