name: Embedded Build
on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_call:
    inputs:
      board:
        required: true
        type: string


jobs:
  arduino_builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
#      - name: Copy required files
#        run: |
#            ls -l
#            cp ./tests/client/test_bmodbus_client.c ./tests/arduino/arduino_unit_tests/test_bmodbus_client.h
#            cp ./tests/unity/unity.c ./tests/arduino/arduino_unit_tests/unity.c
#            cp ./tests/unity/unity.h ./tests/arduino/arduino_unit_tests/unity.h
#            cp ./tests/unity/unity_internals.h ./tests/arduino/arduino_unit_tests/unity_internals.h
#            cp ./bmodbus.h ./tests/arduino/arduino_unit_tests/bmodbus.h
#            cp ./bmodbus.c ./tests/arduino/arduino_unit_tests/bmodbus.c
      - name: Cache Arduino CLI
        uses: actions/cache@v3
        with:
          path: |
            ~/.arduino15
          key: ${{ runner.os }}-arduino-${{ github.sha }}
          restore-keys: ${{ runner.os }}-arduino-

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2
      - name: Arduino CLI init
        continue-on-error: true
        run: |
          arduino-cli config init
      - name: Setting up Arduino CLI Cores
        run: |
          arduino-cli config add board_manager.additional_urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
          arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install adafruit:samd
          arduino-cli core install esp32:esp32
          arduino-cli core install arduino:avr
      - name: Dumping stuff
        run: |
          cd ./tests/arduino
          ls -l 
          ls -l arduino_unit_tests
      - name: Setup CMake
        uses: lukka/get-cmake@latest
        #run: |
        #  sudo apt-get update -q -y
        #  sudo apt-get install -q -y cmake
        #  cmake --version
      - name: Running CMake
        run: |
          cd ./tests/arduino
          mkdir build
          cd build
          cmake ..
          TARGET_BOARD=${{ inputs.board }}
          TARGET_BOARD=build.${TARGET_BOARD//:/\.}
          echo "TARGET_BOARD: $TARGET_BOARD"
          cmake --build . -v --target $TARGET_BOARD
      #- name: Compile Sketch
      #  run: |
      #    cd ./tests/arduino
      #    arduino-cli compile --fqbn "adafruit:samd:adafruit_feather_m4" --build-property "compiler.c.extra_flags=-DUNITY_OUTPUT_CHAR=uut_serial_write"  --build-property "compiler.cpp.extra_flags=-DUNITY_OUTPUT_CHAR=uut_serial_write" --export-binaries arduino_unit_tests
#          arduino-cli config init
#          arduino-cli config set board_manager.additional_urls https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
#          arduino-cli core update-index
#          arduino-cli core install adafruit:samd
#          arduino-cli compile --fqbn adafruit:samd:adafruit_feather_m4 ./tests/arduino/arduino_client_example
#      - name: Compile Sketch
#        uses: arduino/compile-sketches@v1.1.2
#        with:
#          sketch-paths: |
#            - ./tests/arduino/arduino_client_example
#          fqbn: "adafruit:samd:adafruit_feather_m4"
#          platforms: |
#            - name "adafruit:samd"
#            - source-url "https://adafruit.github.io/arduino-board-index/package_adafruit_index.json"
#          verbose: 'true'
