name: Xtensa LX6 ESP32
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
    build_and_test:
      uses: ./.github/workflows/embedded-build.yml
      secrets: inherit
      with:
        board: "esp32:esp32:esp32"

